import React, { useEffect, useState } from "react";
import Admonition from "@theme/Admonition";

// Direct API for development
const API_URL = "https://picsum.photos/v2/list?page=2&limit=10";
// Static file for production (generated by GitHub Actions)
const STATIC_JSON_URL = "/json/photos-data.json";

export default function PhotoGrid({ limit = 8 }) {
  const [photos, setPhotos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    // Choose URL based on environment
    const isDev = process.env.NODE_ENV === "development";
    const url = isDev ? API_URL : STATIC_JSON_URL;

    fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        // Handles format: direct array (Picsum) or { photos: [...] }
        let allPhotos = Array.isArray(data) ? data : data.photos;
        if (!allPhotos || !Array.isArray(allPhotos)) {
          throw new Error("Unexpected data format");
        }
        setPhotos(allPhotos.slice(0, limit));
        setLoading(false);
      })
      .catch((err) => {
        console.error(err);
        setError(err.message);
        setLoading(false);
      });
  }, [limit]);

  if (loading)
    return (
      <div className="text--center margin-vert--lg">Loading photos...</div>
    );

  if (error) {
    return (
      <Admonition type="warning" title="Loading error">
        <p>{error}</p>
      </Admonition>
    );
  }

  if (!photos.length) {
    return (
      <Admonition type="info" title="No photos">
        No photos to display.
      </Admonition>
    );
  }

  return (
    <div className="row">
      {photos.map((photo) => (
        <div key={photo.id} className="col col--4 margin-bottom--lg">
          <div className="card shadow--md">
            <div className="card__image">
              <img
                src={`https://picsum.photos/id/${photo.id}/400/300`}
                alt={photo.author}
                style={{ width: "100%", height: "auto", display: "block" }}
              />
            </div>
            <div className="card__body">
              <h4>{photo.author}</h4>
              <p className="text--small">
                <a
                  href={photo.download_url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  View original
                </a>
              </p>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
