import React from 'react';
// Importe le mapper original + nos composants selon la doc docusaurus
import MDXComponents from '@theme-original/MDXComponents';
import Highlight from '@site/src/components/Highlight';
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocusaurusButton from '@site/src/components/DocusaurusButton';
import Timeline from '@site/src/components/Timeline';
import TimelineItem from '@site/src/components/Timeline/TimelineItem';
import Columns from '@site/src/components/Columns';
import Column from '@site/src/components/Column';
import Card from "@site/src/components/Card";
import CardBody from "@site/src/components/Card/CardBody";
import CardFooter from "@site/src/components/Card/CardFooter";
import CardHeader from "@site/src/components/Card/CardHeader";
import CardImage from "@site/src/components/Card/CardImage";
import Contributor from '@site/src/components/Contributor';
import AvatarContainer from '@site/src/components/Avatar/AvatarContainer';
import AvatarImage from '@site/src/components/Avatar/AvatarImage';
import AvatarIntro from '@site/src/components/Avatar/AvatarIntro';
import AvatarName from '@site/src/components/Avatar/AvatarName';
import AvatarSubtitle from '@site/src/components/Avatar/AvatarSubtitle';
import ImageOnClick from '@site/src/components/ImageOnClick';


export default {
  // Réutilise la correspondance par défaut
  ...MDXComponents,

  img: (props) => {
    const { loading, decoding, className, style, height, width, ...rest } = props;

    return (
      <img
        {...rest}
        // Make sure to keep "height='auto'" (so also disable width) as generated by Docusaurus
        // We shouldn't display the image at full size
        height='auto'
        width=''
        loading={loading || 'lazy'}
        decoding={decoding || 'async'}
        className={`${className || ''}`}

        // Example of how adding extra CSS
        style={{
          borderRadius: '3px',
          ...style,
        }}
      />
    );
  },
  // Ajoute la balise "highlight" à notre composant <Highlight> };
  // `Highlight` recevra tous les props qui ont été passés à `<Highlight>` dans MDX
  Highlight,
  // ajout de la balise ImageOnClick je suit le process docu
 
  TabItem,
  Tabs,
  DocusaurusButton,
  Timeline,
  TimelineItem,
  Columns,
  Column,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  CardImage,
  Contributor,
  AvatarContainer, 
  AvatarImage,
  AvatarIntro,
  AvatarName,
  AvatarSubtitle,
  ImageOnClick
};